USE [InterviewQuestionVictimSelector]
GO

/****** Object:  Table [dbo].[QUESTIONS]    Script Date: 8/10/2018 11:53:01 AM ******/
DROP TABLE [dbo].[QUESTIONS]
GO

/****** Object:  Table [dbo].[QUESTIONS]    Script Date: 8/10/2018 11:53:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QUESTIONS](
	[QUESTION_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[QUESTION] [varchar](1000) NOT NULL,
	[SELECTED] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[QUESTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


